AWSTemplateFormatVersion: 2010-09-09
Resources:

  IWPrivatePartyDomain:
    Type: AWS::CodeArtifact::Domain
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      DomainName: !Sub "${AWS::StackName}-${AWS::Region}-private-3rd-party"
      PermissionsPolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codeartifact:DescribeDomain
              - codeartifact:GetAuthorizationToken
              - codeartifact:GetDomainPermissionsPolicy
              - codeartifact:ListRepositoriesInDomain
              - sts:GetServiceBearerToken
            Effect: Allow
            Principal:
              AWS: 
              - !Ref AWS::AccountId
            Resource: "*"

  IWPrivateMaven3rdPartyRepository:
    Type: AWS::CodeArtifact::Repository
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Description: Repository that contains 3rd party Maven dependencies that are not available on public internet, belongs to the clients ant etc.
      RepositoryName: !Sub "${AWS::StackName}-${AWS::Region}-private-mvn-3rd-party"
      DomainName: !GetAtt IWPrivatePartyDomain.Name
      PermissionsPolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codeartifact:DescribePackage
              - codeartifact:DescribePackageGroup
              - codeartifact:DescribePackageVersion
              - codeartifact:DescribeRepository
              - codeartifact:GetPackageVersionAsset
              - codeartifact:GetPackageVersionReadme
              - codeartifact:GetRepositoryEndpoint
              - codeartifact:ListAssociatedPackages
              - codeartifact:ListPackageGroups
              - codeartifact:ListPackages
              - codeartifact:ListPackageVersionAssets
              - codeartifact:ListPackageVersionDependencies
              - codeartifact:ListPackageVersions
              - codeartifact:ListSubPackageGroups
              - codeartifact:ReadFromRepository
            Effect: Allow
            Principal:
              AWS:
              - !Ref AWS::AccountId
            Resource: "*"
          - Action: 
              - codeartifact:PublishPackageVersion
              - codeartifact:PutPackageMetadata
              - codeartifact:PutPackageOriginConfiguration
              - codeartifact:UpdatePackageVersionsStatus
            Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Resource: "*"

