AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ECConnectInstanceIP:
    Description: EC2 Connect Instance service IP in region
    Type: String
  IWHostedZoneId:
    Description: A domain name for subdomain records initialization
    Type: String
  IWHomepageDomain:
    Description: A domain name
    Type: String
  IWAMIPrivateKeyName:
    Description: Private Key Name
    Type: String
  IWImageId:
    Description: AMI ID
    Default: ami-090c20c6457e1fd80
    Type: AWS::EC2::Image::Id
Resources:

  #
  # Security Groups
  #
  IWWebSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub "web.${AWS::Region}-${AWS::StackName}.sg"
      GroupDescription: HTTP & HTTPS access
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
          Description: HTTP
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
          Description: HTTPS
      Tags:
        - Key: Name
          Value: !Sub "web.${AWS::Region}-${AWS::StackName}.sg"

  IWEC2ConnectSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: !Sub "ec2-connect.${AWS::Region}-${AWS::StackName}.sg"
      GroupDescription: SSH access
      SecurityGroupIngress:
        - CidrIp: !Ref ECConnectInstanceIP
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
          Description: SSH
      Tags:
        - Key: Name
          Value: !Sub "ec2-connect.${AWS::Region}-${AWS::StackName}.sg"

  #
  # Instance
  #
  IWHomepageInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref IWImageId
      InstanceType: t3.micro
      KeyName: 
        Ref: IWAMIPrivateKeyName
      SecurityGroupIds: 
        - !GetAtt IWWebSecurityGroup.GroupId
        - !GetAtt IWEC2ConnectSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: !Sub "ec2-wp-${AWS::Region}-${AWS::StackName}"
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          #
          # Packages
          #
          sudo apt update
          sudo apt upgrade -y
          apt install -y htop s3cmd git
          # sudo apt-get install ec2-instance-connect
          wp plugin update --all

  #
  # Elastic IP addresses
  #
  IWHomepageElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref IWHomepageInstance
      Tags:
        - Key: Name
          Value: !Sub "ec2-wp-eip-${AWS::Region}-${AWS::StackName}"

  #
  # Domain name
  #
  IWHomepageDomainRoute:
    Type: 'AWS::Route53::RecordSetGroup'
    DependsOn:
         - IWHomepageElasticIP
    Properties:
      HostedZoneId: !Ref IWHostedZoneId
      RecordSets:
        - Name: !Ref IWHomepageDomain
          Type: A
          TTL: '900'
          ResourceRecords:
            - !GetAtt IWHomepageInstance.PublicIp
